import { NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import { runSignupGuards } from "@/lib/utils/signup-guards";
import { isAutoGeneratedUsername } from "@/lib/utils/username";
import { normalizeText } from "@/lib/utils/normalize-text";

function isSafeRedirect(path: string): boolean {
  return path.startsWith("/") && !path.startsWith("//") && !path.includes("@") && !path.includes(":");
}

function isFirstOAuthSignup(
  user: { created_at?: string; last_sign_in_at?: string | null },
  username: string | null | undefined
): boolean {
  if (!isAutoGeneratedUsername(username)) {
    return false;
  }

  const createdAt = Date.parse(user.created_at ?? "");
  const lastSignInAt = Date.parse(user.last_sign_in_at ?? "");

  if (Number.isNaN(createdAt) || Number.isNaN(lastSignInAt)) {
    return false;
  }

  return Date.now() - createdAt < 10 * 60 * 1000 && Math.abs(lastSignInAt - createdAt) < 30 * 1000;
}

function blockedOauthRedirect(
  origin: string,
  mode: "signin" | "signup",
  errorCode: "oauth_blocked" | "disposable_email" = "oauth_blocked"
): string {
  const url = new URL(mode === "signup" ? "/auth/signup" : "/auth/login", origin);
  url.searchParams.set("error", errorCode);
  return url.toString();
}

export async function GET(request: Request) {
  const { searchParams, origin } = new URL(request.url);
  const code = searchParams.get("code");
  const mode = searchParams.get("mode") === "signup" ? "signup" : "signin";
  const rawNext = searchParams.get("next") ?? "/feed";
  const next = isSafeRedirect(rawNext) ? rawNext : "/feed";

  if (code) {
    const supabase = await createClient();
    const { error } = await supabase.auth.exchangeCodeForSession(code);
    if (!error) {
      const adminClient = createAdminClient();
      const {
        data: { user },
      } = await supabase.auth.getUser();

      if (user) {
        const { data: profile } = await supabase
          .from("profiles")
          .select("username, display_name, avatar_url")
          .eq("id", user.id)
          .single();

        if (user.email && isFirstOAuthSignup(user, profile?.username)) {
          const guardResult = await runSignupGuards(user.email, request.headers);

          if (!guardResult.ok) {
            await Promise.allSettled([
              adminClient.auth.admin.deleteUser(user.id),
              supabase.auth.signOut(),
            ]);
            const errorCode =
              guardResult.reason === "disposable_email"
                ? "disposable_email"
                : "oauth_blocked";
            return NextResponse.redirect(
              blockedOauthRedirect(origin, mode, errorCode)
            );
          }
        }

        const nextDisplayName =
          typeof user.user_metadata?.display_name === "string" && user.user_metadata.display_name.trim()
            ? user.user_metadata.display_name.trim()
            : typeof user.user_metadata?.full_name === "string" && user.user_metadata.full_name.trim()
              ? user.user_metadata.full_name.trim()
              : typeof user.user_metadata?.name === "string" && user.user_metadata.name.trim()
                ? user.user_metadata.name.trim()
                : null;

        const nextAvatarUrl =
          typeof user.user_metadata?.avatar_url === "string" && user.user_metadata.avatar_url.trim()
            ? user.user_metadata.avatar_url.trim()
            : typeof user.user_metadata?.picture === "string" && user.user_metadata.picture.trim()
              ? user.user_metadata.picture.trim()
              : null;

        const profileUpdates: Record<string, string> = {};

        if (!profile?.display_name && nextDisplayName) {
          profileUpdates.display_name = normalizeText(nextDisplayName);
        }

        if (!profile?.avatar_url && nextAvatarUrl) {
          profileUpdates.avatar_url = nextAvatarUrl;
        }

        if (Object.keys(profileUpdates).length > 0) {
          await adminClient
            .from("profiles")
            .update(profileUpdates)
            .eq("id", user.id);
        }

        if (isAutoGeneratedUsername(profile?.username)) {
          const setupUrl = new URL("/account/username", origin);
          setupUrl.searchParams.set("next", next);
          return NextResponse.redirect(setupUrl.toString());
        }
      }

      return NextResponse.redirect(`${origin}${next}`);
    }
  }

  // Return the user to an error page with instructions
  return NextResponse.redirect(`${origin}/auth/login?error=callback`);
}
