version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 0
    labels:
      - dependencies
    groups:
      npm-security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 0
    labels:
      - ci
    groups:
      github-actions-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
