import type { User } from "@supabase/supabase-js";

export const AUTO_USERNAME_PATTERN = /^user_[0-9a-f]{8}$/;

export function isAutoGeneratedUsername(username: string | null | undefined): boolean {
  if (!username) return false;
  return AUTO_USERNAME_PATTERN.test(username);
}

export function normalizeUsernameCandidate(value: string | null | undefined): string | null {
  if (!value) return null;

  const normalized = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .replace(/_+/g, "_")
    .slice(0, 20);

  return normalized.length >= 3 ? normalized : null;
}

export function getPreferredUsernameCandidates(user: Pick<User, "email" | "user_metadata">): string[] {
  const localPart = user.email?.split("@")[0] ?? null;
  const values = [
    localPart,
    typeof user.user_metadata?.preferred_username === "string" ? user.user_metadata.preferred_username : null,
    typeof user.user_metadata?.user_name === "string" ? user.user_metadata.user_name : null,
    typeof user.user_metadata?.name === "string" ? user.user_metadata.name : null,
    typeof user.user_metadata?.full_name === "string" ? user.user_metadata.full_name : null,
  ];

  return [...new Set(values.map(normalizeUsernameCandidate).filter((value): value is string => !!value))];
}
