"use server";

import { revalidatePath } from "next/cache";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { isAppOpen } from "@/lib/utils/time";
import { getBaseUrl } from "@/lib/constants";
import { runSignupGuards, getClientIp } from "@/lib/utils/signup-guards";
import { isAutoGeneratedUsername } from "@/lib/utils/username";
import { normalizeText } from "@/lib/utils/normalize-text";
import { checkRateLimit } from "@/lib/utils/rate-limit";
import {
  requiredEmailSchema,
  resetPasswordSchema,
  signInSchema,
  signUpSchema,
  usernameSchema,
} from "@/lib/validations";
import type { ActionResult } from "@/lib/types";

function isSafeRedirect(path: string): boolean {
  return path.startsWith("/") && !path.startsWith("//") && !path.includes("@") && !path.includes(":");
}

export async function signUp(formData: FormData): Promise<ActionResult<{ requiresVerification: boolean }>> {
  const captchaToken = formData.get("captchaToken") as string | null;

  if (!captchaToken) {
    return { success: false, error: "Captcha erforderlich" };
  }

  const emailValue = formData.get("email");
  const rawDisplayName = (formData.get("displayName") as string) || undefined;
  const rawData = {
    email: typeof emailValue === "string" ? emailValue : undefined,
    password: formData.get("password") as string,
    username: formData.get("username") as string,
    displayName: rawDisplayName ? normalizeText(rawDisplayName) : undefined,
    acceptTerms: formData.get("acceptTerms") === "true" ? true as const : undefined,
  };

  const parsed = signUpSchema.safeParse(rawData);
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message };
  }

  const headersList = await headers();
  const origin = headersList.get("origin") ?? "https://twohrs.com";
  const guardResult = await runSignupGuards(parsed.data.email, headersList);
  if (!guardResult.ok) {
    return { success: false, error: guardResult.error };
  }

  const supabase = await createClient();

  // Check username availability
  const { data: existingUser } = await supabase
    .from("profiles")
    .select("username")
    .eq("username", parsed.data.username)
    .single();

  if (existingUser) {
    return { success: false, error: "Dieser Username ist bereits vergeben" };
  }

  const { error } = await supabase.auth.signUp({
    email: guardResult.email,
    password: parsed.data.password,
    options: {
      captchaToken,
      emailRedirectTo: `${origin}/auth/callback`,
      data: {
        username: parsed.data.username,
        display_name: parsed.data.displayName || parsed.data.username,
      },
    },
  });

  if (error) {
    // Catch UNIQUE constraint violation on username (TOCTOU race)
    if (error.message?.toLowerCase().includes("unique") || error.message?.toLowerCase().includes("duplicate")) {
      return { success: false, error: "Dieser Username ist bereits vergeben" };
    }
    console.error("Sign-up failed:", error.message);
    return { success: false, error: "Registrierung fehlgeschlagen" };
  }

  return {
    success: true,
    data: { requiresVerification: true },
  };
}

export async function signIn(formData: FormData): Promise<ActionResult> {
  const captchaToken = formData.get("captchaToken") as string | null;

  if (!captchaToken) {
    return { success: false, error: "Captcha erforderlich" };
  }

  const rawData = {
    identifier: formData.get("identifier") as string,
    password: formData.get("password") as string,
  };

  const parsed = signInSchema.safeParse(rawData);
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message };
  }

  const { identifier, password } = parsed.data;
  const normalizedIdentifier = identifier.trim();
  let email: string;

  if (normalizedIdentifier.includes("@")) {
    const parsedEmail = requiredEmailSchema.safeParse(normalizedIdentifier);
    if (!parsedEmail.success) {
      return { success: false, error: "Benutzername oder Passwort falsch" };
    }

    email = parsedEmail.data;
  } else {
    const normalizedUsername = normalizedIdentifier.toLowerCase();
    if (!usernameSchema.safeParse(normalizedUsername).success) {
      return { success: false, error: "Benutzername oder Passwort falsch" };
    }

    const { createAdminClient } = await import("@/lib/supabase/admin");
    const adminClient = createAdminClient();

    const { data: profile } = await adminClient
      .from("profiles")
      .select("id")
      .eq("username", normalizedUsername)
      .single();

    if (!profile) {
      return { success: false, error: "Benutzername oder Passwort falsch" };
    }

    const { data: authUser } = await adminClient.auth.admin.getUserById(profile.id);
    if (!authUser?.user?.email) {
      return { success: false, error: "Benutzername oder Passwort falsch" };
    }

    email = authUser.user.email;
  }

  const supabase = await createClient();

  const { error } = await supabase.auth.signInWithPassword({
    email,
    password,
    options: { captchaToken },
  });

  if (error) {
    if (error.code === "email_not_confirmed") {
      return { success: false, error: "Bitte bestätige zuerst deine E-Mail-Adresse" };
    }
    return { success: false, error: "Benutzername oder Passwort falsch" };
  }

  redirect(isAppOpen() ? "/feed" : "/");
}

export async function signOut(): Promise<void> {
  const supabase = await createClient();
  await supabase.auth.signOut();
  redirect("/");
}

export async function completeOAuthUsername(
  formData: FormData
): Promise<ActionResult<{ next: string }>> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: "Nicht eingeloggt" };
  }

  const rawUsername = formData.get("username");
  const rawNext = formData.get("next");
  const next =
    typeof rawNext === "string" && isSafeRedirect(rawNext) ? rawNext : "/feed";

  const parsedUsername = usernameSchema.safeParse(
    typeof rawUsername === "string" ? rawUsername.trim().toLowerCase() : ""
  );

  if (!parsedUsername.success) {
    return { success: false, error: parsedUsername.error.errors[0].message };
  }

  const { createAdminClient } = await import("@/lib/supabase/admin");
  const adminClient = createAdminClient();

  const { data: profile } = await adminClient
    .from("profiles")
    .select("username")
    .eq("id", user.id)
    .single();

  if (!profile) {
    return { success: false, error: "Profil nicht gefunden" };
  }

  if (!isAutoGeneratedUsername(profile.username)) {
    return { success: true, data: { next } };
  }

  const { data: existingUser } = await adminClient
    .from("profiles")
    .select("id")
    .eq("username", parsedUsername.data)
    .neq("id", user.id)
    .maybeSingle();

  if (existingUser) {
    return { success: false, error: "Dieser Username ist bereits vergeben" };
  }

  const { error } = await adminClient
    .from("profiles")
    .update({
      username: parsedUsername.data,
      updated_at: new Date().toISOString(),
    })
    .eq("id", user.id);

  if (error) {
    if (error.message?.toLowerCase().includes("unique") || error.message?.toLowerCase().includes("duplicate")) {
      return { success: false, error: "Dieser Username ist bereits vergeben" };
    }

    return { success: false, error: "Username konnte nicht gespeichert werden" };
  }

  revalidatePath("/account");
  revalidatePath("/settings");

  return { success: true, data: { next } };
}

export async function requestPasswordReset(formData: FormData): Promise<ActionResult> {
  const captchaToken = formData.get("captchaToken") as string | null;
  if (!captchaToken) {
    return { success: false, error: "Captcha erforderlich" };
  }

  const parsedEmail = requiredEmailSchema.safeParse(
    formData.get("email") as string
  );
  if (!parsedEmail.success) {
    // Always return generic success to prevent account enumeration
    return { success: true };
  }

  // Rate-limit by IP and email to prevent abuse
  const headersList = await headers();
  const clientIp = getClientIp(headersList);

  const ipLimit = checkRateLimit(`auth:reset:ip:${clientIp}`, 5, 60 * 60 * 1000);
  if (!ipLimit.allowed) {
    // Still return generic success to prevent enumeration
    return { success: true };
  }

  const emailLimit = checkRateLimit(`auth:reset:email:${parsedEmail.data}`, 3, 60 * 60 * 1000);
  if (!emailLimit.allowed) {
    return { success: true };
  }

  const supabase = await createClient();
  const baseUrl = getBaseUrl(headersList.get("origin"));

  // Fire and forget — always return success regardless of outcome
  await supabase.auth.resetPasswordForEmail(parsedEmail.data, {
    redirectTo: `${baseUrl}/auth/callback/reset`,
    captchaToken,
  }).catch(() => {
    // Intentionally swallow errors to prevent account enumeration
  });

  return { success: true };
}

export async function completePasswordReset(formData: FormData): Promise<ActionResult> {
  const parsed = resetPasswordSchema.safeParse({
    password: formData.get("password") as string,
    confirmPassword: formData.get("confirmPassword") as string,
  });

  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message };
  }

  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: "Ungültige oder abgelaufene Sitzung" };
  }

  const { error } = await supabase.auth.updateUser({
    password: parsed.data.password,
  });

  if (error) {
    if (error.message?.toLowerCase().includes("same password") || error.message?.toLowerCase().includes("different from")) {
      return { success: false, error: "Das neue Passwort muss sich vom bisherigen unterscheiden" };
    }
    console.error("Password reset failed:", error.message);
    return { success: false, error: "Passwort-Änderung fehlgeschlagen" };
  }

  await supabase.auth.signOut();
  return { success: true };
}
