import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import { UsernameSetupForm } from "@/components/auth/username-setup-form";
import { createClient } from "@/lib/supabase/server";
import {
  getPreferredUsernameCandidates,
  isAutoGeneratedUsername,
} from "@/lib/utils/username";

function isSafeRedirect(path: string): boolean {
  return path.startsWith("/") && !path.startsWith("//") && !path.includes("@") && !path.includes(":");
}

export default async function UsernameSetupPage({
  searchParams,
}: {
  searchParams: Promise<{ next?: string }>;
}) {
  const params = await searchParams;
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    redirect("/auth/login");
  }

  const { data: profile } = await supabase
    .from("profiles")
    .select("username")
    .eq("id", user.id)
    .single();

  const next =
    typeof params.next === "string" && isSafeRedirect(params.next)
      ? params.next
      : "/feed";

  if (!profile) {
    redirect("/auth/login");
  }

  if (!isAutoGeneratedUsername(profile.username)) {
    redirect(next);
  }

  const initialUsername = getPreferredUsernameCandidates(user)[0] ?? "";

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border">
        <div className="mx-auto flex h-14 max-w-lg items-center gap-3 px-4">
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 text-sm text-muted-foreground transition-colors hover:text-foreground"
          >
            <ArrowLeft className="h-4 w-4" />
            Zurück
          </Link>
          <span className="text-sm font-bold tracking-tight">
            two<span className="text-primary">hrs</span>
          </span>
        </div>
      </header>

      <div className="mx-auto max-w-lg space-y-8 px-4 py-8">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Username wählen</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Bevor du loslegst, brauchen wir noch deinen öffentlichen Username.
          </p>
        </div>

        <div className="space-y-4 rounded-lg border border-border bg-card p-6">
          <p className="text-sm text-muted-foreground">
            Dieser Name erscheint in deinem Profil und in deinen Posts. Er ist
            dauerhaft und muss einzigartig sein.
          </p>
          <UsernameSetupForm initialUsername={initialUsername} next={next} />
        </div>
      </div>
    </div>
  );
}
