import { notFound } from "next/navigation";
import { headers } from "next/headers";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { getPostById } from "@/lib/queries/posts";
import { getUnreadMentionCount } from "@/lib/queries/mentions";
import { PostCard } from "@/components/feed/post-card";
import { PostComments } from "./post-comments";
import { AppShell } from "@/app/(app)/app-shell";
import { isAppOpen } from "@/lib/utils/time";
import type { Metadata } from "next";

interface PostPageProps {
  params: Promise<{ id: string }>;
}

export async function generateMetadata({
  params,
}: PostPageProps): Promise<Metadata> {
  const { id } = await params;

  // Use admin client so metadata works for crawlers (no auth, bypasses RLS)
  const supabase = createAdminClient();
  const { data: post } = await supabase
    .from("posts")
    .select("caption, image_url")
    .eq("id", id)
    .single();

  if (!post) {
    return { title: "Post nicht gefunden — twohrs" };
  }

  const title = post.caption
    ? `${post.caption.slice(0, 60)} — twohrs`
    : "Post — twohrs";
  const description = post.caption || "Ein Post auf twohrs";

  const headersList = await headers();
  const host = headersList.get("x-forwarded-host") || headersList.get("host") || "twohrs.com";
  const protocol = host.includes("localhost") ? "http" : "https";
  const postUrl = `${protocol}://${host}/post/${id}`;

  // metadataBase ensures og:image URL uses the alias domain, not the deployment URL
  const baseUrl = `${protocol}://${host}`;

  // og:image is auto-generated by opengraph-image.tsx in this route segment
  return {
    metadataBase: new URL(baseUrl),
    title,
    openGraph: {
      title,
      description,
      type: "article",
      url: postUrl,
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
    },
  };
}

export default async function PostPage({ params }: PostPageProps) {
  const { id } = await params;

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  // Unauthenticated or app closed: show minimal branded page
  if (!user || !isAppOpen()) {
    const adminSupabase = createAdminClient();
    const { data: post } = await adminSupabase
      .from("posts")
      .select(
        "caption, image_url, profiles!posts_user_id_fkey (username, display_name)"
      )
      .eq("id", id)
      .single();

    if (!post) notFound();

    const profile = post.profiles as unknown as {
      username: string;
      display_name: string | null;
    };

    return (
      <div className="flex min-h-screen flex-col items-center justify-center px-4 text-center">
        <div className="mb-6">
          <span className="text-4xl font-bold">twohrs</span>
        </div>
        <p className="text-lg font-medium">
          {profile.display_name || profile.username}
        </p>
        <p className="mt-2 max-w-md text-sm text-muted-foreground">
          {post.caption
            ? post.caption.length > 150
              ? post.caption.slice(0, 147) + "..."
              : post.caption
            : "Ein Post auf twohrs"}
        </p>
        <p className="mt-6 text-sm text-muted-foreground">
          {!user
            ? "Melde dich an, um diesen Post zu sehen."
            : "twohrs ist gerade geschlossen. Komm heute Nacht wieder!"}
        </p>
        <Link
          href={!user ? "/auth/login" : "/"}
          className="mt-4 rounded-lg bg-primary px-6 py-2.5 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
        >
          {!user ? "Anmelden" : "Zur Startseite"}
        </Link>
      </div>
    );
  }

  // Authenticated + app open: full post view
  const post = await getPostById(id);
  if (!post) notFound();

  const { data: profile } = await supabase
    .from("profiles")
    .select("username, is_admin, moderation_strikes")
    .eq("id", user.id)
    .single();

  const isAdmin = profile?.is_admin ?? false;
  const unreadMentionCount = await getUnreadMentionCount(user.id);

  return (
    <AppShell
      username={profile?.username}
      unreadMentionCount={unreadMentionCount}
      moderationStrikes={profile?.moderation_strikes ?? 0}
    >
      <div className="mx-auto max-w-lg px-4 py-4">
        <Link
          href="/feed"
          className="mb-4 inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"
        >
          <ArrowLeft className="h-4 w-4" />
          Zurück zum Feed
        </Link>

        <PostCard post={post} currentUserId={user.id} hideCommentSection isAdmin={isAdmin} />

        <div className="mt-4 overflow-hidden rounded-lg border border-border bg-card p-4">
          <PostComments postId={post.id} isAdmin={isAdmin} />
        </div>
      </div>
    </AppShell>
  );
}
